### ISSUE TITLE
CairoShell under Windows 2016 Core (Hyper-V)

### ISSUE THREAD

**Issue by hafedh-trimeche** [dremin/cairoshell#7] opened 2017-06-30 14:10 UTC
Hello,
After installation of CairoShell under Windows 2016 Hyper-V (no GUI) an exception raised with message as "CairoDesktop. WindowsTrayHooks.dll can't be loaded".

Would CairoShell be installed under Core editions of Windows 2016 (Hyper-V & Server Core with no GUI)?

Regards.

**Comment by DakotaBlake** [comment] 2017-06-30 15:58
I'm assuming it can't register WindowsTrayHooks.dll because there is no System Tray on Core.

**Comment by dremin** [comment] 2017-07-08 02:23
Did you install the prerequisite MS Visual C++ Redistributable? If so, it is indeed possible there are APIs missing on Core. I'll see what I can do to handle this more gracefully.

**Comment by hafedh-trimeche** [comment] 2017-07-08 16:51
Done but same exception !

![2017-07-08 17_47_34-uimachineviewnormalclasswindow](https://user-images.githubusercontent.com/988584/27987462-f47c7b34-6405-11e7-8933-c787c67a7279.png)

**Comment by dremin** [comment] 2017-07-08 19:05
Cairo starts on my fresh Server 2016 Core install without modifications. In fact, I even get a functional system tray after installing the required [Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53587). The error in your screen shot may be unrelated to the tray error, but I am surprised that you are not seeing the unhandled exception window.

Unfortunately, it seems drag-and-drop operations are not supported on the Core OS, so I am not able to select any apps in the App Grabber. I may look at allowing double-click as an alternative to drag-drop to bypass this.

I have uploaded a new release that should fix a few crashers I found, and it also fixes the display of the Cairo settings window on a server OS. Please give it a go and let me know if it works for you. If it doesn't, I'd like to look further into why yours is crashing.

**Comment by hafedh-trimeche** [comment] 2017-07-09 19:39
Please find attached log events collected from Hyper-V 20016 edition:

Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at MS.Win32.PresentationCore.UnsafeNativeMethods+WICCodec.CreateColorTransform(System.Windows.Media.Imaging.BitmapSourceSafeMILHandle ByRef)
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(System.Windows.Media.Imaging.BitmapFrame, System.Windows.Media.Imaging.BitmapSourceSafeMILHandle, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Windows.Media.Imaging.BitmapPalette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(System.Windows.Media.Imaging.BitmapDecoder, System.Collections.ObjectModel.ReadOnlyCollection`1<System.Windows.Media.Imaging.BitmapFrame>)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at CairoDesktop.Desktop.Window_SourceInitialized(System.Object, System.EventArgs)
   at System.Windows.Window.OnSourceInitialized(System.EventArgs)
   at System.Windows.Window.CreateSourceWindow(Boolean)
   at System.Windows.Window.ShowHelper(System.Object)
   at CairoDesktop.Startup.Main(System.String[])


---------------------------------------------------------------------------------------
Faulting application name: CairoDesktop.exe, version: 0.2.6357.41117, time stamp: 0x592b8c7a
Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c4f0
Exception code: 0xe0434352
Fault offset: 0x0000000000017788
Faulting process id: 0x4cc
Faulting application start time: 0x01d2f8e94c9d5830
Faulting application path: C:\Program Files\Cairo Shell\CairoDesktop.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e4cc9c72-b121-41b3-b2a7-f76087edefc5
Faulting package full name: 
Faulting package-relative application ID: 
---------------------------------------------------------------------------------------
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: CairoDesktop.exe
P2: 0.2.6357.41117
P3: 592b8c7a
P4: PresentationCore
P5: 4.6.1586.0
P6: 575a214d
P7: 4200
P8: d
P9: System.Windows.Markup.XamlParse
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER99B5.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CairoDesktop.exe_9bb570237ec091bd71ae287a655f8abe7219e6ec_a644e594_04aaa4c2

Analysis symbol: 
Rechecking for solution: 0
Report Id: e4cc9c72-b121-41b3-b2a7-f76087edefc5
Report Status: 97
Hashed bucket: 
---------------------------------------------------------------------------------------
Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at MS.Win32.PresentationCore.UnsafeNativeMethods+WICCodec.CreateColorTransform(System.Windows.Media.Imaging.BitmapSourceSafeMILHandle ByRef)
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(System.Windows.Media.Imaging.BitmapFrame, System.Windows.Media.Imaging.BitmapSourceSafeMILHandle, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Windows.Media.Imaging.BitmapPalette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(System.Windows.Media.Imaging.BitmapDecoder, System.Collections.ObjectModel.ReadOnlyCollection`1<System.Windows.Media.Imaging.BitmapFrame>)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at CairoDesktop.Desktop.Window_SourceInitialized(System.Object, System.EventArgs)
   at System.Windows.Window.OnSourceInitialized(System.EventArgs)
   at System.Windows.Window.CreateSourceWindow(Boolean)
   at System.Windows.Window.ShowHelper(System.Object)
   at CairoDesktop.Startup.Main(System.String[])

---------------------------------------------------------------------------------------
Faulting application name: CairoDesktop.exe, version: 0.2.6398.26788, time stamp: 0x59612a0a
Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c4f0
Exception code: 0xe0434352
Fault offset: 0x0000000000017788
Faulting process id: 0x5a8
Faulting application start time: 0x01d2f8e9d600c31d
Faulting application path: C:\Program Files\Cairo Shell\CairoDesktop.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 01f5e35f-c73b-4b0f-928b-50d6a4b52ccf
Faulting package full name: 
Faulting package-relative application ID:

**Comment by dremin** [comment] 2017-07-10 00:19
@hafedh-trimeche Thanks for the exception printout. I am going to install Hyper-V Server 2016 to try and reproduce. Based on the exception, I have something you can try which should allow Cairo to start.

1. In the `C:\Program Files\Cairo Shell` folder, open `CairoDesktop.Configuration.dll.config` in Notepad.
1. Find `<setting name="EnableDesktop"` and change the value from `True` to `False`.
1. Open `CairoDesktop.exe`. Cairo should hopefully start, minus the Desktop icons.

**Comment by dremin** [comment] 2017-07-10 01:47
@hafedh-trimeche Okay, the Hyper-V Server OS is missing even more DLLs than Core, so it can't display images properly in WPF. I've uploaded a new build that should at least get Cairo running for you, but it will be severely limited (missing images, no desktop navigation). App Grabber will crash, which means first run will also crash, so second run should work.

**Comment by hafedh-trimeche** [comment] 2017-07-10 04:52
The exception generated by the last release:
(Inner Exception)
Date and Time:         10/07/2017 06:47:57
Machine Name:          WIN-M3ME87N735M
IP Address:            10.0.2.15
Current User:          WIN-M3ME87N735M\Virtual User

Application Domain:    CairoDesktop.exe
Assembly Codebase:     file:///C:/Program Files/Cairo Shell/CairoDesktop.exe
Assembly Full Name:    CairoDesktop, Version=0.2.6399.39021, Culture=neutral, PublicKeyToken=null
Assembly Version:      0.2.6399.39021
Assembly Build Date:   09/07/2017 22:40:42

Exception Source:      PresentationCore
Exception Type:        System.DllNotFoundException
Exception Message:     Unable to load DLL 'WindowsCodecsExt.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Exception Target Site: CreateColorTransform

---- Stack Trace ----
   MS.Win32.PresentationCore.WICCodec.CreateColorTransform(ppWICColorTransform As BitmapSourceSafeMILHandle&)
       CairoDesktop.exe: N 00000
   System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
       CairoDesktop.exe: N 00074
   System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
       CairoDesktop.exe: N 02328
   System.Windows.Media.Imaging.BitmapImage.EndInit()
       CairoDesktop.exe: N 00127
   MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(xamlType As XamlType, obj As Object, begin As Boolean)
       CairoDesktop.exe: N 00088



(Outer Exception)
Date and Time:         10/07/2017 06:47:58
Machine Name:          WIN-M3ME87N735M
IP Address:            10.0.2.15
Current User:          WIN-M3ME87N735M\Virtual User

Application Domain:    CairoDesktop.exe
Assembly Codebase:     file:///C:/Program Files/Cairo Shell/CairoDesktop.exe
Assembly Full Name:    CairoDesktop, Version=0.2.6399.39021, Culture=neutral, PublicKeyToken=null
Assembly Version:      0.2.6399.39021
Assembly Build Date:   09/07/2017 22:40:42

Exception Source:      PresentationFramework
Exception Type:        System.Windows.Markup.XamlParseException
Exception Message:     Initialization of 'System.Windows.Media.Imaging.BitmapImage' threw an exception.
Exception Target Site: RewrapException

---- Stack Trace ----
   System.Windows.Markup.XamlReader.RewrapException(e As Exception, baseUri As Uri)
       CairoDesktop.exe: N 00023
   System.Windows.FrameworkTemplate.LoadTemplateXaml(templateReader As XamlReader, currentWriter As XamlObjectWriter)
       CairoDesktop.exe: N 01051
   System.Windows.FrameworkTemplate.LoadTemplateXaml(objectWriter As XamlObjectWriter)
       CairoDesktop.exe: N 00139
   System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(container As DependencyObject, componentConnector As IComponentConnector, styleConnector As IStyleConnector, affectedChildren As List`1, templatedNonFeChildrenField As UncommonField`1)
       CairoDesktop.exe: N 00781
   System.Windows.FrameworkTemplate.LoadContent(container As DependencyObject, affectedChildren As List`1)
       CairoDesktop.exe: N 00168
   System.Windows.StyleHelper.ApplyTemplateContent(dataField As UncommonField`1, container As DependencyObject, templateRoot As FrameworkElementFactory, lastChildIndex As Int32, childIndexFromChildID As HybridDictionary, frameworkTemplate As FrameworkTemplate)
       CairoDesktop.exe: N 00287
   System.Windows.FrameworkTemplate.ApplyTemplateContent(templateDataField As UncommonField`1, container As FrameworkElement)
       CairoDesktop.exe: N 00082
   System.Windows.FrameworkElement.ApplyTemplate()
       CairoDesktop.exe: N 00146
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 00120
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Border.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00475
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Control.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00097
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.VirtualizingStackPanel.MeasureChild(generator As IItemContainerGenerator&, itemStorageProvider As IContainItemStorage&, parentItemStorageProvider As IContainItemStorage&, parentItem As Object&, hasUniformOrAverageContainerSizeBeenSet As Boolean&, computedUniformOrAverageContainerSize As Double&, computedUniformOrAverageContainerPixelSize As Double&, computedAreContainersUniformlySized As Boolean&, items As IList&, item As Object&, children As IList&, childIndex As Int32&, visualOrderChanged As Boolean&, isHorizontal As Boolean&, childConstraint As Size&, viewport As Rect&, cacheSize As VirtualizationCacheLength&, cacheUnit As VirtualizationCacheLengthUnit&, foundFirstItemInViewport As Boolean&, firstItemInViewportOffset As Double&, stackPixelSize As Size&, stackPixelSizeInViewport As Size&, stackPixelSizeInCacheBeforeViewport As Size&, stackPixelSizeInCacheAfterViewport As Size&, stackLogicalSize As Size&, stackLogicalSizeInViewport As Size&, stackLogicalSizeInCacheBeforeViewport As Size&, stackLogicalSizeInCacheAfterViewport As Size&, mustDisableVirtualization As Boolean&, isBeforeFirstItem As Boolean, isAfterFirstItem As Boolean, isAfterLastItem As Boolean, skipActualMeasure As Boolean, skipGeneration As Boolean, hasBringIntoViewContainerBeenMeasured As Boolean&, hasVirtualizingChildren As Boolean&)
       CairoDesktop.exe: N 01086
   System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(constraint As Size, lastPageSafeOffset As Nullable`1&, previouslyMeasuredOffsets As List`1&, lastPagePixelSize As Nullable`1&, remeasure As Boolean)
       CairoDesktop.exe: N 03008
   System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00228
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   MS.Internal.Helper.MeasureElementWithSingleChild(element As UIElement, constraint As Size)
       CairoDesktop.exe: N 00075
   System.Windows.Controls.ItemsPresenter.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00019
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   MS.Internal.Helper.MeasureElementWithSingleChild(element As UIElement, constraint As Size)
       CairoDesktop.exe: N 00075
   System.Windows.Controls.ScrollContentPresenter.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00292
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Grid.MeasureCell(cell As Int32, forceInfinityV As Boolean)
       CairoDesktop.exe: N 00324
   System.Windows.Controls.Grid.MeasureCellsGroup(cellsHead As Int32, referenceSize As Size, ignoreDesiredSizeU As Boolean, forceInfinityV As Boolean, hasDesiredSizeUChanged As Boolean&)
       CairoDesktop.exe: N 00205
   System.Windows.Controls.Grid.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 01185
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.ScrollViewer.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00698
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Border.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00475
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Control.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00097
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Border.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00475
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Grid.MeasureCell(cell As Int32, forceInfinityV As Boolean)
       CairoDesktop.exe: N 00324
   System.Windows.Controls.Grid.MeasureCellsGroup(cellsHead As Int32, referenceSize As Size, ignoreDesiredSizeU As Boolean, forceInfinityV As Boolean, hasDesiredSizeUChanged As Boolean&)
       CairoDesktop.exe: N 00205
   System.Windows.Controls.Grid.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 01185
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Border.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00475
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.Controls.Grid.MeasureOverride(constraint As Size)
       CairoDesktop.exe: N 00242
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       CairoDesktop.exe: N 01343
   System.Windows.UIElement.Measure(availableSize As Size)
       CairoDesktop.exe: N 00625
   System.Windows.ContextLayoutManager.UpdateLayout()
       CairoDesktop.exe: N 00536
   System.Windows.ContextLayoutManager.UpdateLayoutCallback(arg As Object)
       CairoDesktop.exe: N 00034
   System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       CairoDesktop.exe: N 00145
   System.Windows.Media.MediaContext.RenderMessageHandlerCore(resizedCompositionTarget As Object)
       CairoDesktop.exe: N 00156
   System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(resizedCompositionTarget As Object)
       CairoDesktop.exe: N 00114
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback As Delegate, args As Object, numArgs As Int32)
       CairoDesktop.exe: N 00097
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen(source As Object, callback As Delegate, args As Object, numArgs As Int32, catchHandler As Delegate)
       CairoDesktop.exe: N 00054





![cairodesktop exe unhandledexception](https://user-images.githubusercontent.com/988584/28003200-be3f54ae-6533-11e7-843f-fef7c411fdc4.png)

**Comment by dremin** [comment] 2017-07-11 03:51
@hafedh-trimeche Sorry, does Cairo run if you try opening it again? That error is coming from the App Grabber which starts automatically on the first time.

**Comment by hafedh-trimeche** [comment] 2017-07-11 04:49
Yes, it runs but no item can be added to application's list.

**Comment by dremin** [comment] 2017-07-30 05:56
@hafedh-trimeche I have fixed the crash and made the changes mentioned above in the latest release. Please give it a try!

**Comment by hafedh-trimeche** [comment] 2017-07-31 07:58
Installation OK.
the Grap App works but selecting menu item failed. It would manually set via text box.

![2017-07-31 08_52_35-dremin_cairoshell_ cairo is a customizable intuitive desktop environment for wi](https://user-images.githubusercontent.com/988584/28768110-5ed8c986-75ce-11e7-9099-8e4030c8dea2.png)

**Comment by dremin** [comment] 2017-07-31 19:13
@hafedh-trimeche Glad it's working. You can double-click items in the "Installed Applications" list to move them over to the Programs menu. This list looks at the start menu folders. For apps that aren't added to the start menu folder, the window that I use for Browse seems to be missing in the HyperV OS so I will see if I can fall back to something else.

**Comment by dremin** [comment] 2017-08-02 05:49
@hafedh-trimeche Please try the latest release I just uploaded, the browse button should work for you now.

**Comment by hafedh-trimeche** [comment] 2017-08-02 08:09
Hi,
It's OK for the Browse button.
Changing Theme to White doesn't work.
The first menu item not highlighted
![2017-08-02 08_53_13-vpn - vmware remote console](https://user-images.githubusercontent.com/988584/28863752-16602006-7762-11e7-86c1-c2a668c715a9.png)

Manually sorting Program Items would be a nice feature.

**Comment by hafedh-trimeche** [comment] 2017-08-07 10:40
![2017-08-07 11_35_14-firebird website - directory index](https://user-images.githubusercontent.com/988584/29023373-41e9aef2-7b65-11e7-9c53-8ead759b3354.png)

![2017-08-07 11_34_36-firebird website - directory index](https://user-images.githubusercontent.com/988584/29023370-3d8bc49e-7b65-11e7-9b43-7454b10f4502.png)
Hi,
Is it possible to force Destop Refresh under Windows Core editions by periodically  invoking a windows API ( "SHChangeNotify" or equivalent) ?
![2017-08-07 11_33_52-firebird website - directory index](https://user-images.githubusercontent.com/988584/29023365-39696c5e-7b65-11e7-99cc-ca08bf253ed5.png)

**Comment by dremin** [comment] 2017-08-08 05:22
@hafedh-trimeche I'm not quite sure what you are asking. Could you please explain? I'm not sure Cairo is doing anything that warrants calling that API.

**Comment by hafedh-trimeche** [comment] 2017-08-08 07:02
After long desktop inactivity delay the screen switches off and when moving mouse cursor or clicking keyboard button to wake it up, the desktop is not displayed as expected.

Is there solution which can force the desktop to be periodically refreshed an maintained  in good display state?

**Comment by dremin** [comment] 2017-08-09 05:12
@hafedh-trimeche Oh, I understand what you mean. Unfortunately I believe this is usually dependent on video drivers, outside of application control. I haven't seen this problem on either a physical Hyper-V box or a VMware VM.

**Comment by dremin** [comment] 2017-09-02 19:16
I'm going to close this since Cairo is working as much as is feasible on Hyper-V Server. Thanks for reporting this, I can see that Cairo is great to have on Core OS!

**Closed by dremin** 2017-09-02 19:16 UTC
